### ISSUE TITLE
Upgraded to 1.6.1 and now can't compile anything

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#530]
I was having problems with the -D parameter to eosio-cpp on v1.5.0 and was told v1.6.1 fixed these problems so I upgraded.  now I can't compile anything.  I'm getting these kinds of errors:
```
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "token.cpp"
No compilation database found in /Users/ekkis/dev or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
In file included from /Users/ekkis/dev/token.cpp:1:
/Users/ekkis/dev/token.hpp:3:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
Error while processing /Users/ekkis/dev/token.cpp.
abigen error
```
the release notes say absolutely nothing about needing to initialise these databases or how, and googling for the errors has turned up nothing but hints that Ninja and CMake can generate these but no idea how

can we please document this for those poor sods like me that decide to upgrade?

p.s. the command I'm using is:
```
eosio-cpp -D=DEBUG -D'__BURN__="burn"' token.cpp -E -dD -o - |grep BURN
```
which yields the above but:
```
eosio-cpp -D=DEBUG -D'__BURN__="burn"' token.cpp -o token.wasm --abigen
```
breaks with a similar error (breaks on `#include "./token.hpp"` and doesn't include all the database notices)

**Comment by jeffreyssmith2nd** [comment]
@ekkis What path did you take to upgrade? Have you tried uninstalling and reinstalling cdt?

**Comment by ekkis** [comment]
I use brew on OSX and it was a fresh upgrade so reinstalling wouldn't help.  the issue seems to be that the `-E -dD` functionality is broken in 1.6.1.  it worked fine in 1.5.0

**Comment by ekkis** [comment]
I'm closing this issue because the problem isn't really with compiling.  if I don't use the above-named parameters the code compiles fine.  there's an issue more specific to that here: https://github.com/EOSIO/eosio.cdt/issues/534#issuecomment-512925634
