### ISSUE TITLE
Cannot build on WSL Ubuntu 16.04

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eosio.cdt#130]
Hi, when I run `./build.sh` on Windows 10 WSL Ubuntu 16.04 I get this error:

```bash
Scanning dependencies of target clangFrontend
[ 40%] Building CXX object tools/clang/lib/Driver/CMakeFiles/clangDriver.dir/ToolChains/Arch/ARM.cpp.o
[ 40%] Building CXX object tools/clang/lib/Driver/CMakeFiles/clangDriver.dir/ToolChains/Arch/Mips.cpp.o
In file included from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/include/llvm/ADT/StringRef.h:13:0,
                 from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/tools/clang/include/clang/Basic/DiagnosticIDs.h:20,
                 from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/tools/clang/include/clang/Basic/Diagnostic.h:18,
                 from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/tools/clang/include/clang/Driver/Driver.h:13,
                 from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/tools/clang/lib/Driver/ToolChains/Arch/Mips.h:13,
                 from /mnt/d/eos-dev/eosio.cdt/eosio_llvm/tools/clang/lib/Driver/ToolChains/Arch/Mips.cpp:10:
/mnt/d/eos-dev/eosio.cdt/eosio_llvm/include/llvm/ADT/STLExtras.h:21:34: fatal error: llvm/ADT/SmallVector.h: No such file or directory
compilation terminated.
tools/clang/lib/Driver/CMakeFiles/clangDriver.dir/build.make:374: recipe for target 'tools/clang/lib/Driver/CMakeFiles/clangDriver.dir/ToolChains/Arch/Mips.cpp.o' failed
make[5]: *** [tools/clang/lib/Driver/CMakeFiles/clangDriver.dir/ToolChains/Arch/Mips.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
```
