### ISSUE TITLE
Multiple variant generates same name

### ISSUE THREAD

**Issue by jnordberg** [EOSIO/eosio.cdt#336]
Only the first variant will get added to the ABI def, to reproduce:

```cpp
#include <eosiolib/eosio.hpp>

using namespace eosio;

struct testing {
    std::variant<uint8_t, uint16_t> v1;
    std::variant<uint16_t, uint32_t> v2;
    EOSLIB_SERIALIZE(testing, (v1)(v2))
};

CONTRACT test : public eosio::contract {
public:
  using contract::contract;
  ACTION dummy(testing t){};
};

EOSIO_DISPATCH(test, (dummy));
```

```
$ eosio-abigen -version
eosio-abigen version 1.4.1
$ eosio-abigen -contract test -output test.json test.cpp && cat test.json
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <dummy> does not have a ricardian contract
{
    "____comment": "This file was generated with eosio-abigen. DO NOT EDIT Fri Dec 28 10:24:07 2018",
    "version": "eosio::abi/1.1",
    "structs": [
        {
            "name": "dummy",
            "base": "",
            "fields": [
                {
                    "name": "t",
                    "type": "testing"
                }
            ]
        },
        {
            "name": "testing",
            "base": "",
            "fields": [
                {
                    "name": "v1",
                    "type": "variant_"
                },
                {
                    "name": "v2",
                    "type": "variant_"
                }
            ]
        }
    ],
    "types": [],
    "actions": [
        {
            "name": "dummy",
            "type": "dummy",
            "ricardian_contract": ""
        }
    ],
    "tables": [],
    "ricardian_clauses": [],
    "variants": [
        {
            "name": "variant_",
            "types": ["uint8","uint16"]
        }
    ],
    "abi_extensions": []
}
```

---

Possibly related is that omitting `EOSLIB_SERIALIZE(testing, (v1)(v2))` causes abigen to fail with:

```
test.cpp:1:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/eosiolib/eosio.hpp:6:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/eosiolib/action.hpp:7:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/eosiolib/datastream.hpp:28:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr.hpp:12:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr/precise.hpp:12:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr/precise/core.hpp:23:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr/detail/core14.hpp:13:
In file included from /usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr/detail/core14_loophole.hpp:29:
/usr/local/Cellar/eosio.cdt/1.4.1/opt/eosio.cdt/bin/../include/boost/pfr/detail/offset_based_getter.hpp:63:3: error: static_assert failed "Member sequence does not indicate correct size for struct type!"
  static_assert(sizeof(U) == sizeof(S), "Member sequence does not indicate correct size for struct type!");
```

**Comment by jnordberg** [comment]
Another possibly related bug is that `using std::variant` causes abigen to segfault:

Segfault:

```cpp
#include <eosiolib/eosio.hpp>

using namespace eosio;
using std::variant;

struct testing {
    variant<uint8_t, uint16_t> nani;
    EOSLIB_SERIALIZE(testing, (nani))
};

CONTRACT test : public eosio::contract {
public:
  using contract::contract;
  ACTION dummy(testing t){};
};

EOSIO_DISPATCH(test, (dummy));
```

Ok:

```cpp
#include <eosiolib/eosio.hpp>

using namespace eosio;

struct testing {
    std::variant<uint8_t, uint16_t> nani;
    EOSLIB_SERIALIZE(testing, (nani))
};

CONTRACT test : public eosio::contract {
public:
  using contract::contract;
  ACTION dummy(testing t){};
};

EOSIO_DISPATCH(test, (dummy));
```

**Comment by jnordberg** [comment]
The problem persists in version 1.5.0

**Comment by jnordberg** [comment]
Variant ABI generation works in 1.6.1. Still segfaults though if declared with `using std::variant`

**Comment by jeffreyssmith2nd** [comment]
Confirmed that `using std::variant` still segfaults on 1.6.2

**Comment by jeffreyssmith2nd** [comment]
#521 experiences a similar issue when `using std::tuple`.

**Comment by jeffreyssmith2nd** [comment]
Since the error is actually with the using-declaration, closing this issue in favor of Issue #558 that specifically tracks this problem.
