### ISSUE TITLE
How does multi_index indexed_by work in 1.3.1?

### ISSUE THREAD

**Issue by lovecactus** [EOSIO/eosio.cdt#173]
Hi guys,

I updated my code according to 1.3.1 release note. But it seems I didn't get "indexed_by" working correctly and not able to find any help in the doc (doc is still for 1.2.x).

``` 
         struct [[eosio::table]] tidaccount {
            uint64_t pkey;           // opaque, will use available_primary_key()
            string   tidname;
            asset    balance;
            uint64_t primary_key()const { return pkey; }
            string   by_tidname()const { return tidname; } // for secondary key
            EOSLIB_SERIALIZE(tidaccount,(pkey)(tidname)(balance))
         };



typedef eosio::multi_index< "tidaccount"_n, tidaccount, indexed_by<"tidname"_n, const_mem_fun > tidaccounts; ```

It gets error like this:
include/eosio.token/eosio.token.hpp:97:90: error: use of class template 'const_mem_fun' requires template arguments
         typedef eosio::multi_index< "tidaccount"_n, tidaccount, indexed_by<"tidname"_n, const_mem_fun > tidaccounts;
                                                                                         ^
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:30:8: note: template is declared here
struct const_mem_fun


Can any one provide a sample of how indexed_by working in 1.3.1? 
Thanks!

**Comment by larryk85** [comment]
Currently, we don't support `string` for secondary indices, but you could use an `eosio::name`, so
your table would look like
```c++
struct [[eosio::table]] tidaccount {
   uint64_t pkey;           // opaque, will use available_primary_key()
   name   tidname;
   asset    balance;
   uint64_t primary_key()const { return pkey; }
   uint64_t   by_tidname()const { return tidname.value; } // for secondary key
   EOSLIB_SERIALIZE(tidaccount,(pkey)(tidname)(balance))
};
```
change to `typedef eosio::multi_index< "tidaccount"_n, tidaccount, indexed_by<"tidname"_n, const_mem_fun<tidaccount, uint64_t, &tidaccount::by_tidname> > tidaccounts; `.
